"""adds user table

Revision ID: 2a3402cf4310
Revises: 
Create Date: 2021-08-26 07:40:39.561219

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2a3402cf4310'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
